<script lang="ts" setup>
import Call from "~/components/ui/call.vue";
import LocationContact from "~/components/ui/location-contact.vue";
</script>
<template>
  <section class="tw-py-36">
    <div
      class="tw-flex tw-flex-col tw-items-center tw-justify-center tw-w-full"
    >
      <div
        class="tw-divider !tw-font-medium tw-text-[var(--primary)] tw-w-[10rem] tw-m-auto"
      >
        <h2 class="tw-text-[1.125rem]">03</h2>
      </div>
      <h2
        class="tw-text-[3.125rem] tw-mt-3 tw-capitalize tw-text-[#212122] tw-font-semibold"
      >
        our energy solutions
      </h2>
      <p
        class="tw-text-[1.125rem] tw-text-center tw-m-auto tw-w-[29rem] tw-mt-3 tw-capitalize tw-text-[#353C40] tw-font-semibold"
      >
        The text is an example of text that can be replaced in the same space.
        This text was generated by the Arabic text generator.
      </p>
    </div>
    <div
      class="tw-flex tw-items-start lg:tw-flex-row tw-flex-col tw-mt-20 tw-gap-20"
    >
      <div class="lg:tw-w-fit tw-w-full">
        <img
          class="lg:tw-w-fit tw-w-full lg:tw-h-full tw-h-[600px] tw-object-cover"
          src="~/assets/images/654e90af882fc70586f9daa9_pittsburgh-image-industrial-x-webflow-template.png"
          alt=""
        />
      </div>
      <div class="tw-flex-1 tw-flex tw-flex-col tw-gap-5">
        <div
          v-for="(_, index) in Array(5)"
          :tabindex="index"
          :key="index"
          class="tw-collapse tw-pb-10 tw-rounded-none tw-border-r-0 tw-border-t-0 tw-border-l-0 tw-collapse-plus !tw-border-b-[#e4eaed] !tw-border-b tw-border"
        >
          <div
            class="tw-collapse-title tw-text-2xl tw-text-secondary tw-text-[1.875rem] tw-font-medium"
          >
            Branch Name
          </div>
          <div class="tw-collapse-content">
            <p class="tw-text-tertiary tw-text-[1.125rem]">
              This text is an example of text that can be replaced in the same
              space. It was generated by the Arabic text generator, where you
              can generate similar text or many others like it.
            </p>
            <div class="tw-flex tw-items-start tw-justify-between tw-mt-10">
              <div class="tw-flex-1">
                <div class="tw-flex tw-gap-2 tw-items-center">
                  <component :is="Call" />
                  <h3 class="tw-text-[1.2rem] tw-text-secondary">Call Us</h3>
                </div>
                <div class="tw-flex-col tw-flex tw-mt-4">
                  <div>
                    <h2 class="tw-text-tertiary tw-txt-[1.125rem]">
                      EmailAddress:
                    </h2>
                    <a
                      href="order@hpi-sa.com"
                      target="_blank"
                      class="tw-text-tertiary tw-txt-[1.125rem]"
                    >
                      order@hpi-sa.com
                    </a>
                  </div>
                </div>
                <div class="tw-flex-col tw-flex tw-mt-4">
                  <div>
                    <h2 class="tw-text-tertiary tw-txt-[1.125rem]">Phone:</h2>
                    <a
                      href="tel:966138167179"
                      target="_blank"
                      class="tw-text-tertiary tw-txt-[1.125rem]"
                    >
                      966138167179
                    </a>
                  </div>
                </div>
              </div>
              <div class="tw-flex-1">
                <div class="tw-flex tw-gap-2 tw-items-center">
                  <component :is="LocationContact" />
                  <h3 class="tw-text-[1.2rem] tw-text-secondary">Location</h3>
                </div>
                <div class="tw-flex-col tw-flex tw-mt-4">
                  <div>
                    <h2 class="tw-text-tertiary tw-txt-[1.125rem]">
                      P.O. Box 4083, Dammam 34331, Kingdom of Saudi Arabia
                    </h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style></style>
