<script lang="ts" setup>
import BaseContainer from "~/components/core/BaseContainer.vue";
import BaseImage from "~/components/core/BaseImage.vue";
import Slash from "~/components/ui/slash.vue";
import LoadingSvg from "~/assets/svg/loading-svgrepo-com.svg";
import image from "~/assets/images/654d61bacd06c8284a65d8c2_pittsburgh-image-industrial-x-webflow-template.png";
import CallUs from "~/components/ui/call-us.vue";
import Location from "~/components/ui/location.vue";
</script>
<template>
  <section class="tw-py-20">
    <BaseContainer>
      <div class="tw-grid tw-grid-cols-2 tw-items-end tw-gap-20">
        <div>
          <div class="tw-flex tw-items-center tw-gap-2">
            <p class="tw-text-basecolor tw-text-[1.125rem]">08</p>
            <component :is="Slash" />
          </div>
          <div class="tw-mt-5">
            <h2
              class="tw-text-[3.125rem] tw-max-w-[34rem] tw-mt-3 tw-capitalize tw-text-[#212122] tw-font-semibold"
            >
              Visit Our Site
            </h2>
            <p
              class="tw-mt-2 tw-text-[#353C40] tw-text-[18px] tw-font-normal tw-line-clamp-2"
            >
              Renew this text. This is an example of text that can be replaced
              in the same space. It was generated by the Arabic text generator,
              where you can generate.
            </p>
          </div>
        </div>
        <!--  -->
        <div class="tw-flex tw-gap-20">
          <h2 class="tw-text-[#212122] tw-text-[18px]">Branch Name</h2>
        </div>
      </div>
    </BaseContainer>
    <div class="tw-w-full tw-mt-16">
      <BaseImage
        class_styles="tw-size-full tw-object-cover tw-max-h-[37.5rem]"
        :thumbnail="image"
        :place_holder="LoadingSvg"
      />
    </div>
    <div class="-tw-mt-[16rem]">
      <div class="tw-w-[40%] tw-bg-[#212122] tw-relative tw-z-50 tw-py-10">
        <BaseContainer>
          <div class="tw-flex tw-flex-col tw-mb-5">
            <h3 class="tw-capitalize tw-text-[30px] tw-text-white">
              Branch Name
            </h3>
            <p class="tw-text-[#D4DEE4] tw-text-[18px]">
              It seems like you might have intended to ask for a translation but
              didn’t provide a specific text. Could you clarify what you'd like
              translated?
            </p>
          </div>
          <div class="tw-flex tw-items-center tw-gap-10 tw-flex-wrap">
            <div class="tw-flex tw-flex-col tw-flex-1">
              <div class="tw-flex tw-items-center tw-gap-4">
                <component :is="CallUs" />
                <h2
                  class="tw-text-white tw-text-[1.5rem] tw-font-medium tw-font-medium"
                >
                  Call Us
                </h2>
              </div>
              <div class="tw-mt-3 tw-flex tw-gap-2">
                <h2 class="tw-text-[#697B86]">Email Address:</h2>
                <NuxtLink target="_blank" class="tw-text-white"
                  >e@hpi-sa.com</NuxtLink
                >
              </div>
              <div class="tw-mt-3 tw-flex tw-gap-2">
                <h2 class="tw-text-[#697B86]">Phone</h2>
                <NuxtLink target="_blank" class="tw-text-white"
                  >(123) 456 - 789</NuxtLink
                >
              </div>
            </div>
            <div class="tw-flex tw-flex-col tw-flex-1">
              <div class="tw-flex tw-items-center tw-gap-4">
                <component :is="Location" />
                <h2
                  class="tw-text-white tw-text-[1.5rem] tw-font-medium tw-font-medium"
                >
                  Our website
                </h2>
              </div>
              <div class="tw-mt-3">
                <h2 class="tw-text-[#B7C2C8] tw-text-[18px] tw-w-[13em]">
                  P.O. Box 4083, Dammam 34331, Saudi Arabia
                </h2>
              </div>
            </div>
          </div>
        </BaseContainer>
      </div>
    </div>
  </section>
</template>

<style></style>
