<script lang="ts" setup>
import BaseContainer from "~/components/core/BaseContainer.vue";
import Slash from "~/components/ui/slash.vue";
</script>
<template>
  <section class="tw-py-20">
    <BaseContainer>
      <div class="tw-flex tw-items-center tw-gap-2">
        <p class="tw-text-basecolor tw-text-[1.125rem]">08</p>
        <component :is="Slash" />
      </div>
      <div class="tw-mt-5">
        <h2
          class="tw-text-[3.125rem] tw-max-w-[34rem] tw-mt-3 tw-capitalize tw-text-[#212122] tw-font-semibold"
        >
          Follow Us on Social Media
        </h2>
        <p
          class="tw-mt-2 tw-text-[#353C40] tw-max-w-xl tw-text-[18px] tw-font-normal tw-line-clamp-2"
        >
          Renew this text. This is an example of text that can be replaced in
          the same space. It was generated by the Arabic text generator, where
          you can generate.
        </p>
      </div>
      <!-- Cards -->
      <div class="tw-flex tw-gap-5 tw-mt-20 ">
        <a target="_blank" href=""
          class="tw-bg-[#F6F8F9] tw-p-20 tw-h-[282px] tw-justify-center tw-flex tw-items-center tw-flex-1 tw-flex-col"
        >
            <Icon name="bi:facebook" size="40" class="tw-text-[#212122]" />
        </a target="_blank">
        <a target="_blank" href=""
          class="tw-bg-[#F6F8F9] tw-p-20 tw-h-[282px] tw-justify-center tw-flex tw-items-center tw-flex-1 tw-flex-col"
        >
            <Icon name="mdi:twitter" size="40" class="tw-text-[#212122]" />
        </a target="_blank">
        <a target="_blank" href=""
          class="tw-bg-[#F6F8F9] tw-p-20 tw-h-[282px] tw-justify-center tw-flex tw-items-center tw-flex-1 tw-flex-col"
        >
            <Icon
              name="akar-icons:twitch-fill"
              size="40"
              class="tw-text-[#212122]"
            />
        </a target="_blank">
        <a target="_blank" href=""
          class="tw-bg-[#F6F8F9] tw-p-20 tw-h-[282px] tw-justify-center tw-flex tw-items-center tw-flex-1 tw-flex-col"
        >
          <Icon
            name="tdesign:logo-youtube-filled"
            size="40"
            class="tw-text-[#212122]"
          />
        </a target="_blank">
      </div>
    </BaseContainer>
  </section>
</template>

<style></style>
